apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /apps/grafananfsfolderlogs
    server: 10.192.148.20
    readOnly: false

